import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { HomePage } from "../components/MyComponent";

const Home: NextPage = () => {
  const [counter, setCounter] = useState(0);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <HomePage counter={counter} />
        <button
          className="border-2 bg-black text-white hover:bg-black/70 px-3 py-2"
          onClick={() => setCounter(counter + 1)}
        >
          Increment
        </button>
      </main>
    </>
  );
};

export default Home;
